USE [PROJETCC_K];
GO

EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all";
GO

DROP TABLE IF EXISTS ACHAT;
DROP TABLE IF EXISTS VENTE;
DROP TABLE IF EXISTS CONTROLE_TECHNIQUE;
DROP TABLE IF EXISTS REPARATION_PIECES;
DROP TABLE IF EXISTS REPARATION;
DROP TABLE IF EXISTS ENTRETIEN_PIECES;
DROP TABLE IF EXISTS ENTRETIEN;
DROP TABLE IF EXISTS PIECE;
DROP TABLE IF EXISTS VEHICULE;
DROP TABLE IF EXISTS CREDIT;
DROP TABLE IF EXISTS ASSURANCE;
DROP TABLE IF EXISTS UTILISATEUR;

GO

EXEC sp_MSforeachtable "ALTER TABLE ? CHECK CONSTRAINT all";
GO

CREATE TABLE UTILISATEUR(
   idUtilisateur INT IDENTITY(1,1) PRIMARY KEY,
   Civ BIT NOT NULL,
   Nom VARCHAR(50) NOT NULL,
   Prenom VARCHAR(50) NOT NULL,
   Email VARCHAR(100) NOT NULL,
   NumeroTel VARCHAR(15) NOT NULL,
   AdresseNum INT NOT NULL,
   AdresseVoie VARCHAR(50) NOT NULL,
   AdresseVille VARCHAR(50),
   AdresseCP INT NOT NULL,
);
GO

CREATE TABLE ASSURANCE(
   idAssurance INT IDENTITY(1,1) PRIMARY KEY,
   TypeAssurance VARCHAR(50),
   Mensualite DECIMAL(15,2),
   DateDebut VARCHAR(50) NOT NULL
);
GO

CREATE TABLE CREDIT(
   idCredit INT IDENTITY(1,1) PRIMARY KEY,
   MontantTotal INT,
   Mensualite INT,
   Duree INT,
   Taux INT
);
GO

CREATE TABLE PIECE(
   idPiece INT IDENTITY(1,1) PRIMARY KEY,
   NomPiece VARCHAR(50) NOT NULL,
   Marque VARCHAR(50),
   Prix INT,
);
GO

CREATE TABLE VEHICULE(
   idVehicule INT IDENTITY(1,1) PRIMARY KEY,
   Marque VARCHAR(50) NOT NULL,
   Modele VARCHAR(50) NOT NULL,
   Annee INT NOT NULL,
   Valeur DECIMAL(15,2),
   Kilometrage INT NOT NULL,
   Couleur VARCHAR(50) NOT NULL,
   Puissance INT,
   StatutDisp BIT NOT NULL,
   Immat VARCHAR(50) NOT NULL UNIQUE,
   Photo VARBINARY(MAX),
   idUtilisateur INT,
   CONSTRAINT FK_UTILISATEUR_VEHICULE FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR(idUtilisateur)
);
GO

CREATE TABLE ENTRETIEN(
   idEntretien INT IDENTITY(1,1) PRIMARY KEY,
   DateEntretien VARCHAR(50) NOT NULL,
   Cout INT,
   ModePaiement VARCHAR(50),
   idVehicule INT NOT NULL,
   CONSTRAINT FK_VEHICULE_ENTRETIEN FOREIGN KEY (idVehicule) REFERENCES VEHICULE(idVehicule)
);
GO

CREATE TABLE ENTRETIEN_PIECES (
   idEntretien INT NOT NULL,
   idPiece INT NOT NULL,
   Quantite INT,
   PRIMARY KEY (idEntretien, idPiece),
   CONSTRAINT FK_ENTRETIEN_PIECE FOREIGN KEY (idEntretien) REFERENCES ENTRETIEN(idEntretien),
   CONSTRAINT FK_PIECE_ENTRETIEN FOREIGN KEY (idPiece) REFERENCES PIECE(idPiece)
);
GO

CREATE TABLE REPARATION(
   idReparation INT IDENTITY(1,1) PRIMARY KEY,
   DateReparation VARCHAR(50) NOT NULL,
   Designation VARCHAR(50) NOT NULL,
   Cout INT,
   ModePaiement VARCHAR(50),
   idVehicule INT NOT NULL,
   CONSTRAINT FK_VEHICULE_REPARATION FOREIGN KEY (idVehicule) REFERENCES VEHICULE(idVehicule)
);
GO

CREATE TABLE REPARATION_PIECES (
   idReparation INT NOT NULL,
   idPiece INT NOT NULL,
   Quantite INT,
   PRIMARY KEY (idReparation, idPiece),
   CONSTRAINT FK_REPARATION_PIECE FOREIGN KEY (idReparation) REFERENCES REPARATION(idReparation),
   CONSTRAINT FK_PIECE_REPARATION FOREIGN KEY (idPiece) REFERENCES PIECE(idPiece)
);
GO

CREATE TABLE CONTROLE_TECHNIQUE(
   idControleTechnique INT IDENTITY(1,1) PRIMARY KEY,
   DateCT VARCHAR(50) NOT NULL,
   Cout INT,
   ModePaiement VARCHAR(50),
   idVehicule INT NOT NULL,
   CONSTRAINT FK_VEHICULE_CONTROLE_TECHNIQUE FOREIGN KEY (idVehicule) REFERENCES VEHICULE(idVehicule)
);
GO

CREATE TABLE VENTE(
   idVente INT IDENTITY(1,1) PRIMARY KEY,
   PrixVente DECIMAL(15,2),
   DateVente VARCHAR(50) NOT NULL,
   ModePaiement VARCHAR(50),
   idUtilisateur INT NOT NULL,
   idVehicule INT NOT NULL,
   CONSTRAINT FK_UTILISATEUR_VENTE FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR(idUtilisateur),
   CONSTRAINT FK_VEHICULE_VENTE FOREIGN KEY (idVehicule) REFERENCES VEHICULE(idVehicule)
);
GO

CREATE TABLE ACHAT(
   idAchat INT IDENTITY(1,1) PRIMARY KEY,
   DateAchat VARCHAR(50) NOT NULL,
   ModePaiement VARCHAR(50),
   idVehicule INT NOT NULL,
   idCredit INT,
   idAssurance INT,
   idUtilisateur INT NOT NULL,
   CONSTRAINT FK_UTILISATEUR_ACHAT FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR(idUtilisateur),
   CONSTRAINT FK_VEHICULE_ACHAT FOREIGN KEY (idVehicule) REFERENCES VEHICULE(idVehicule),
   CONSTRAINT FK_CREDIT_ACHAT FOREIGN KEY (idCredit) REFERENCES CREDIT(idCredit),
   CONSTRAINT FK_ASSURANCE_ACHAT FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
);
GO

